### ISSUE TITLE
Game is not started

### ISSUE THREAD

**Issue by shurupov** [lamka-tatya/otus_js#21]
При первом запуске, если не нажать кнопку обновления (стрелочки по кругу в правой части окна), и нажать кнопку старт (треугольник внизу слева), то игра не начнётся.
1. Запускаем приложение (или жмём F5 в браузере).
2. Жмём старт
Ожидаемое поведение: игра жизнь началась.
Фактическое поведение: ничего не происходит.

**Comment by lamka-tatya** [comment]
Будет исправлено в рамках https://github.com/lamka-tatya/otus_js/issues/23
