### ISSUE TITLE
Arrow buttons don't work.

### ISSUE THREAD

**Issue by shurupov** [lamka-tatya/otus_js#22]
Кнопки previous и next не работают или их действие не очевидно.
1. Жмём на любую их них.
Ожидаемое поведение: должно что-то меняться, вероятно должно появиться следующее/предыдущее состояние жизни.
Фактическое поведение: ничего не меняется.

**Comment by lamka-tatya** [comment]
Это поведение будет реализовано в полной версии программы, на выпускном проекте.
